ARCreateEntry  
ARDeleteEntry  
ARGetEntry  
ARGetEntryBLOB  
ARGetEntryBlock  
ARGetEntryStatistics  
ARGetListEntry  
ARGetListEntryBlocks  
ARGetListEntryWithFields  
ARGetMultipleEntries  
ARMergeEntry  
ARSetEntry